CR-1258 logging
ONSdigital/census-rh-service pull request #88
Opened 2020-10-22 17:17 UTC by akritisinhaa

2020-10-28 09:20 UTC, andrewjohnysons commented on src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImpl.java
> +      log.with("uprn", uprn).warn("No cases returned for uprn");
Not sure that these should be warnings. At best info in my opinion.
Just hasn't found any cases - woopey doo - who's going to read that?
That's just my personal opinion

2020-10-28 09:21 UTC, andrewjohnysons commented on src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImpl.java
> +      log.with("caseId", caseId).warn("Failed to retrieve Case from storage");
again - why not just info

2020-10-28 09:22 UTC, andrewjohnysons commented on src/main/java/uk/gov/ons/ctp/integration/rhsvc/service/impl/CaseServiceImpl.java
> +          .warn("The UPRN of the referenced Case and the provided Address UPRN must be matching");
Again - here -

2020-10-28 09:32 UTC, andrewjohnysons requested changes
CaseServiceImpl - line 108 I'd add the caseID to th exception to identify it, 
 add something to that CTPException on line 108 which is why I am requesting changes :-)

2020-10-28 10:01 UTC, akritisinhaa commented
@andrewjohnysons made changes to line 108 as suggested

2020-10-28 11:55 UTC, andrewjohnysons approved these changes

2020-10-29 11:07 UTC, devenrawat approved these changes

2020-10-29 12:11 UTC, rpcatling requested changes
Just a couple of small additions. There are two calls to the `error` logging method (in the case and UAC receiver code). Please can we add the exception parameter for a stack trace.

2020-10-29 12:18 UTC, akritisinhaa commented
@rpcatling added the stack trace and also updated the pom to point to latest framework version

2020-10-29 13:49 UTC, rpcatling approved these changes

2020-10-29 13:52 UTC, merged